### ISSUE TITLE
Create additional log methods

### ISSUE THREAD

**Issue by codeasashu** [myoperator/centrallog-py#1]
### Description

The centrallog currently miss a logging class. Implement a `logging` class which:

1. Can be imported in any python package as `from myoperator.centrallog import logging`
2. Must have following methods:

```
dlog
slog
clog
```

### Milestones:

- [x] Create `dlog`, `clog`, `slog` methods
- [x] `log` method should accept `acl` parameter as kwargs
- [x] Write unit test cases for `dlog`, `clog`, `slog` methods based on below constraints

### Constraints

- Additional methods should have same signature as the standard `log` method of python logging module.
- the module should pass all standard unit test cases by python logging module

**Comment by sandeep-rawat1** [comment]
for all logs other than dlog, slog and clog, the default value for acl is 1(i.e developer).
