### ISSUE TITLE
Add configure method

### ISSUE THREAD

**Issue by codeasashu** [myoperator/centrallog-py#2]
### Description

Currently, `centrallog-py` misses a `configure` method. Add a singleton `configure` method, which when called anywhere inside any project during a request cycle, must give the same instance of an initialized object. 

The `configure` method must be able to receive following params:

- service name (required field)
- hostname (ip address)
- uid (unique identifier)

```py
from myoperator.centrallog import logger

logger.configure('my service') # valid

logger.configure('my service', '127.0.0.1') # valid

logger.configure('my service', '127.0.0.1',  'abcdef123') # valid

logger.configure() # invalid. Atleast service name is required
```

### Behaviour

- If service name is not provided, it should throw an exception
- If ip address is not provided, try to use the server hostname on which application is running
- if uid is not provided, generate a unique alphanumeric string
- Configure must work as singleton. i.e. if call in any dependent classes or packages, it should reuse the already instantiated object.
- it should not modify any functionality of standard python `logging`  package.

### Milestones

- [x] Create configure method with above behaviour
- [x] Write unit tests
- [x] Python logging unit tests must pass

**Comment by sandeep-rawat1** [comment]
Done!
